#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 1512000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 384000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

echo 0 > /sys/class/android_usb/android0/enable
echo 0FCE > /sys/class/android_usb/android0/idVendor
echo 6146 > /sys/class/android_usb/android0/idProduct
echo mass_storage,adb > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/enable

stop adbd

# trigger amber LED
echo '255' > /sys/class/leds/blue/brightness
echo '255' > /sys/class/leds/red/brightness
echo '0' > /sys/class/leds/green/brightness
# trigger button-backlight
echo '200' > /sys/class/leds/button-backlight/brightness

cat /dev/input/event0 > /dev/keycheck&
sleep 3

# poweroff LED and button-backlight
echo '0' > /sys/class/leds/blue/brightness
echo '0' > /sys/class/leds/red/brightness
echo '0' > /sys/class/leds/green/brightness
echo '0' > /sys/class/leds/button-backlight/brightness

kill -9 $!
